spring:
  application:
    name: vsm

  jpa:
    hibernate:
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5435/vsm
    username: postgres
    password: postgres

hibernate:
  format_sql: true
  show_sql: true

server:
  port: 8081

redis:
  host: localhost
  port: 6379
  password: 1111
